/*
 * HazeStar Project
 * ==================================
 * SLFCG whoru123@nate.com
 * ==================================
 * 
 */

package constants.Programs;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import constants.GameConstants;
import server.Items.ItemInformation;
import tools.Pair;

/**
 *
 * @author Administrator
 */
public class SearchToCode extends javax.swing.JFrame
{

	/**
	 * Creates new form SearchToCode
	 */
	public SearchToCode()
	{
		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		this.setLocation((screenSize.width - 877) / 2, (screenSize.height - 530) / 2);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        검색어 = new javax.swing.JTextField();
        장비 = new javax.swing.JRadioButton();
        아이템 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        출력L = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setResizable(false);

        jLabel1.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel1.setText("Item name");

        장비.setText("Equip");
        장비.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                장비ActionPerformed(evt);
            }
        });

        아이템.setText(" item");
        아이템.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                아이템ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(출력L);

        jButton1.setText("Divided and saved");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save by one space");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(장비)
                        .addGap(147, 147, 147)
                        .addComponent(아이템)
                        .addGap(284, 284, 284))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(검색어, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(검색어, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(장비)
                    .addComponent(아이템))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButton1ActionPerformed
		String name = JOptionPane.showInputDialog(null, "파일명을 입력해 주십시오");
		FileOutputStream out = null;
		try
		{
			out = new FileOutputStream("" + name + ".txt", false);
			out.write(임시1.toString().getBytes());
		}
		catch (Exception ex)
		{
		}
		finally
		{
			try
			{
				if (out != null) out.close();
			}
			catch (IOException ex)
			{
			}
			JOptionPane.showMessageDialog(null, "저장이 완료되었습니다.");
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void 장비ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_장비ActionPerformed
		아이템.setSelected(false);
		체크[1] = false;
		체크[0] = true;
	}// GEN-LAST:event_장비ActionPerformed

	private void 아이템ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_아이템ActionPerformed
		장비.setSelected(false);
		체크[0] = false;
		체크[1] = true;
	}// GEN-LAST:event_아이템ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButton3ActionPerformed
		if (!체크[0] && !체크[1])
		{
			JOptionPane.showMessageDialog(null, "분류를 선택해 주십시오.");
			return;
		}
		출력.clear();
		출력L.setModel(출력);
		임시1 = "";
		임시2 = "";
		List<String> retItems = new ArrayList<String>();
		for (Pair<Integer, String> itemPair : ItemInformation.getInstance().getAllItems())
		{
			if (itemPair.getRight().toLowerCase().contains(검색어.getText()))
			{
				if (체크[0])
				{
					if (GameConstants.isEquip(itemPair.getLeft()))
					{
						임시1 = 임시1 + itemPair.getLeft() + ", ";
						임시2 = 임시2 + itemPair.getLeft() + " - " + itemPair.getRight() + "\r\n";
						retItems.add(itemPair.getLeft() + " - " + itemPair.getRight());
					}
				}
				else if (체크[1])
				{
					if (!GameConstants.isEquip(itemPair.getLeft()))
					{
						임시1 = 임시1 + itemPair.getLeft() + ", ";
						임시2 = 임시2 + itemPair.getLeft() + " - " + itemPair.getRight() + "\r\n";
						retItems.add(itemPair.getLeft() + " - " + itemPair.getRight());
					}
				}
			}
		}
		if (retItems != null && retItems.size() > 0)
		{
			for (String singleRetItem : retItems)
			{
				출력.addElement(singleRetItem.toString());
			}
			출력L.setModel(출력);
		}
		else
		{
			JOptionPane.showMessageDialog(null, "발견된 아이템이 없습니다.");
		}

	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButton2ActionPerformed
		String name = JOptionPane.showInputDialog(null, "파일명을 입력해 주십시오");
		FileOutputStream out = null;
		try
		{
			out = new FileOutputStream("" + name + ".txt", false);
			out.write(임시2.toString().getBytes());
		}
		catch (Exception ex)
		{
		}
		finally
		{
			try
			{
				if (out != null) out.close();
			}
			catch (IOException ex)
			{
			}
			JOptionPane.showMessageDialog(null, "저장이 완료되었습니다.");
		}
	}// GEN-LAST:event_jButton2ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[])
	{

		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new SearchToCode().setVisible(true);
			}
		});
	}

	public static String 임시2 = "";
	public static String 임시1 = "";
	private boolean 체크[] = { false, false };
	public static DefaultListModel 출력 = new DefaultListModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField 검색어;
    private javax.swing.JRadioButton 아이템;
    private javax.swing.JRadioButton 장비;
    private javax.swing.JList 출력L;
    // End of variables declaration//GEN-END:variables
}
