package server.Maps.MapObject;

public enum MapleMapObjectType {
    NPC, PLAYERNPC, MONSTER, ITEM, PLAYER, DOOR, SUMMON, SUBSUMMON, SHOP, MIST, REACTOR, HIRED_MERCHANT, EXTRACTOR, MINI_GAME, ANDROID, RUNE, ARROWFLATTER, DRAGON, ObtacleAtom, DemianSword;
}
